apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1c0x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1c0x
    app.kubernetes.io/part-of: ci1t-43256-0023-app
  name: devfile-sample-1c0x
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1c0x
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1c0x
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0023-tenant/ci1t-43256-0023-app/devfile-sample-1c0x@sha256:c8f0170d47fbc547bc334c703c31191d1f711b06554641771175c3a4252e8e8b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
